### PR TITLE
Add default algorithm of MD5 in readDigestChallenge() if not algorith…

### PR DESCRIPTION
**Pull request by jeremyrumpf**
Add default algorithm of MD5 in readDigestChallenge() if no algorithm token is found in the auth header.

### CODE REVIEW

**Comment by vzhn** [comment]
@jeremyrumpf Thank you for contribution!

**Comment by sebphil** [comment]
@vzhn when can we expect a new release with this fix please?

**Comment by vzhn** [comment]
Well, I'll try to find my GPG keys. If I find them, there will be a new release soon.

**Comment by vzhn** [comment]
@sebphil release is ready: https://repo1.maven.org/maven2/io/github/vzhn/netty-http-authenticator/1.2/

**Pull request merged**
